### PR TITLE
Bugfix/navbar profile picture

### LINKED ISSUE #556: Profile Picture in navbar not updated on change

### LINKED ISSUE #560: Profile picture in navbar has wrong aspect ratio

### PR DESCRIPTION
**Pull request by tobias-wiese**
# Description

- Fixes issues #560 #556 
- Closes #560 
- Closes #556 

## Reason for this PR
- Picture in navbar had wrong ratio
- Picture in navbar was not updated on change

## Changes in this PR
- picture now is loaded as background image for a div, that corrects the ration bug
- if a user changes the profile picture, the picture in the navbar is updated via subscribing to a vuex mutation
- update the profile picture via a random url parameter, that way, the browser does not use its cached (the path to the image stays the same, the randomnr triggers the update without further effects)

## Type of change (remove all that don't apply)
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manually tested all use cases this could alter

**Test Configuration**:
- OS: Windows 
- Browser: Firefox Chrome

- Frontend: (remove all that don't apply)
  - [x] Development build
- Backend: (remove all that don't apply)
  - [x] deployed development build

# Checklist: (remove all that don't apply)

- [x] I have performed a self-review of my own code
- [x] My changes generate no new linting warnings or console warnings
- [x] I have updated the CHANGELOG.md to include any changes made in this PR

# Notes:
- As the img is load via URL as a background for the div, we are not able to write proper E2E test, but we can be sure that the image is loaded, that is provided on the URL after successful change
- The profile picture does not automatically update for a user if an admin changes it. For that purpose, I could implement a pulling method, that reloads the image repeatedly after a specified time. But I do not think, that this is a problem

### CODE REVIEW

File: src/use/store/mutations.ts [hunk 1]
```diff
@@ -22,4 +22,7 @@ export const mutations: MutationTree<State> & Mutations = {
     [MutationTypes.SET_USER](state: State, payload: Student | Lecturer | Admin) {
         state.user = payload;
     },
+    [MutationTypes.UPDATE_PROFILE_PICTURE](state: State, payload: boolean) {
```
Comment (theovier) [inline src/use/store/mutations.ts:25]:
```suggestion
    [MutationTypes.FORCE_UPDATE_PROFILE_PICTURE]() {
```

File: src/use/store/mutation-types.ts [hunk 2]
```diff
@@ -2,4 +2,5 @@ export enum MutationTypes {
     SET_LOGGEDIN = "SET_LOGGEDIN",
     SET_MODAL = "SET_MODAL",
     SET_USER = "SET_USER",
+    UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE",
```
Comment (theovier) [inline src/use/store/mutation-types.ts:5]:
```suggestion
    FORCE_UPDATE_PROFILE_PICTURE = "FORCE_UPDATE_PROFILE_PICTURE",
```

File: src/components/navigation/navbar/desktop/common/profile/ProfileMenu.vue [hunk 3]
```diff
@@ -31,17 +35,30 @@
...
                 busy.value = false;
             });
 
+            function loadProfilePicture() {
+                pictureBaseUrl = process.env.VUE_APP_API_BASE_URL + "/user-management/users/" + user.value.username + "/image?";
+                profilePicture.value = pictureBaseUrl;
+            }
+
+            store.subscribe((mutation) => {
+                if (mutation.type === MutationTypes.UPDATE_PROFILE_PICTURE) {
```
Comment (theovier) [inline src/components/navigation/navbar/desktop/common/profile/ProfileMenu.vue:57]:
```suggestion
                if (mutation.type === MutationTypes.FORCE_UPDATE_PROFILE_PICTURE) {
```

File: src/components/profile/ProfilePictureSection.vue [hunk 4]
```diff
@@ -164,6 +169,7 @@
                         }
                         case action.DELETE: {
                             deleteProfilePicture();
+                            store.commit(MutationTypes.UPDATE_PROFILE_PICTURE, true);
```
Comment (theovier) [inline src/components/profile/ProfilePictureSection.vue:172]:
```suggestion
                            store.commit(MutationTypes.FORCE_UPDATE_PROFILE_PICTURE, true);
```

File: src/components/profile/ProfilePictureSection.vue [hunk 5]
```diff
@@ -142,6 +146,7 @@
                 const result = await handler.handleResponse(response);
                 if (result) {
                     fallbackPicture.value = selectedPicture.value;
+                    store.commit(MutationTypes.UPDATE_PROFILE_PICTURE, true);
```
Comment (theovier) [inline src/components/profile/ProfilePictureSection.vue:149]:
```suggestion
                    store.commit(MutationTypes.FORCE_UPDATE_PROFILE_PICTURE, true);
```

**Review by theovier — APPROVED** [review]
